apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ileap-demo-server
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/way-ileap-demo-prod/ghcr/way-platform/ileap-go/ileap:latest
        args:
        - demo-server
        ports:
        - containerPort: 8080
